#!/bin/sh
n=$(git ls-files -m|grep -v version.go|wc -l)
s=$(git log -1 --pretty=format:%s)
if [[ ${n} -eq 0 && ${s} != version.go* ]]; then
  v=$(git describe --tag --long --abbrev=7)
  sed -i "s;\"[^\"]*\?\";\"${v}\";g" version.go
  git add version.go
  git commit -m "version.go: bump to version ${v}"
fi
